# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Actual Budget"
version: "1.0.3-alpine"
slug: actualbudget
description: "A local-first personal finance tool"
url: "https://github.com/actualbudget/actual-server"
arch:
  - aarch64
  - amd64
ingress: true
ingress_port: 5006
ports:
  5006/tcp: 5006
ports_description:
  5006/tcp: "Actual Budget web interface"
panel_icon: mdi:currency-usd
init: false
image: jlongster/actual-server
webui: "http://[HOST]:[PORT:5006]"
