# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Telegraf
version: "1.1.0"
slug: telegraf
description: Run the Telegraf docker image on Home Assistant
url: "https://github.com/jnimmo/hass-addons/telegraf"
arch:
  - armv7
  - aarch64
  - amd64
options:
  config_path: "Hello world..."
schema:
  message: "str?"
image: telegraf
map:
  - config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
