# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Telegraf
version: "0.0.1"
slug: "hass_telegraf"
description: Run the Telegraf docker image on Home Assistant
url: "https://github.com/jnimmo/hass-addons/telegraf"
arch:
  - armv7
  - aarch64
  - amd64
options:
  custom_conf: {"enabled": true, "location": "/config/telegraf.conf"}
  hostname: "homeassistant.local"
schema:
  custom_conf: {
      "enabled": "bool",
      "location": "str"
    }
image: "telegraf"
map:
  - config:ro
host_network: true
