# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Telegraf
version: "0.0.1"
slug: telegraf
description: Run the Telegraf docker image on Home Assistant
url: "https://github.com/jnimmo/hass-addons/telegraf"
arch:
  - armv7
  - aarch64
  - amd64
image: telegraf
map:
  - config:ro
